const express=require('express'),nodemailer=require('nodemailer'),app=express()
app.use(express.json({limit:'50mb'}))
const TOKEN=process.env.AGENT_TOKEN||'mailflow-agent-2026'
const jobs=new Map()
function auth(req,res,next){if(req.headers['x-agent-token']!==TOKEN)return res.status(401).json({error:'Unauthorized'});next()}
app.get('/health',(req,res)=>res.json({status:'ok',version:'1.0.0',jobs:jobs.size,uptime:process.uptime()}))
function getSMTP(email){const d=(email||'').split('@')[1]?.toLowerCase()||'';const c={'gmail.com':{host:'smtp.gmail.com',port:587},'googlemail.com':{host:'smtp.gmail.com',port:587},'outlook.com':{host:'smtp-mail.outlook.com',port:587},'hotmail.com':{host:'smtp-mail.outlook.com',port:587},'yahoo.com':{host:'smtp.mail.yahoo.com',port:587},'yahoo.co.in':{host:'smtp.mail.yahoo.com',port:587},'icloud.com':{host:'smtp.mail.me.com',port:587},'me.com':{host:'smtp.mail.me.com',port:587}};return c[d]||{host:'smtp.'+d,port:587}}
function parseCSV(csv){const lines=csv.split('\n').map(function(l){return l.trim()}).filter(function(l){return l.length>0});var accounts=[];for(var i=0;i<lines.length;i++){var line=lines[i];if(line.toLowerCase().startsWith('email,'))continue;var parts=line.split(',');if(parts.length<2||!parts[0].includes('@'))continue;var email=parts[0].trim();var password=parts.slice(1).join(',').trim().replace(/^"|"$/g,'');var cfg=getSMTP(email);accounts.push({email:email,password:password,host:cfg.host,port:cfg.port})}return accounts}
function buildAttachments(raw){if(!raw||!Array.isArray(raw)||raw.length===0)return [];var out=[];for(var i=0;i<raw.length;i++){var a=raw[i];try{var content=a.content||a.data||'';var filename=a.filename||a.name||('attachment'+(i+1));var contentType=a.contentType||a.mimeType||'application/octet-stream';if(!content||content.length<10){console.log('[Agent] Skipping empty attachment:',filename);continue;}out.push({filename:filename,content:Buffer.from(content,'base64'),contentType:contentType});}catch(e){console.log('[Agent] Attachment error:',e.message);}}console.log('[Agent] Built',out.length,'attachments for nodemailer');return out;}
async function sendOne(smtp,opts){var t=nodemailer.createTransport({host:smtp.host,port:smtp.port||587,secure:false,requireTLS:true,auth:{user:smtp.email,pass:smtp.password},connectionTimeout:15000,greetingTimeout:10000,socketTimeout:15000,tls:{rejectUnauthorized:false}});var r=await t.sendMail(opts);t.close();return r}
app.post('/send',auth,async function(req,res){var jobId=req.body.jobId,contacts=req.body.contacts,subject=req.body.subject,fromName=req.body.fromName,htmlBody=req.body.htmlBody,textBody=req.body.textBody,smtpCsv=req.body.smtpCsv,smtpList=req.body.smtpList,rawAttachments=req.body.rawAttachments||req.body.attachments||[];console.log('[Agent] Job received:',jobId,'contacts:',contacts&&contacts.length,'attachments:',rawAttachments.length);if(!jobId||!contacts||!subject||!htmlBody)return res.status(400).json({error:'Missing required fields'});var smtps=smtpCsv?parseCSV(smtpCsv):(smtpList||[]);if(smtps.length===0)return res.status(400).json({error:'No SMTP accounts'});var jobAttachments=buildAttachments(rawAttachments);var job={id:jobId,status:'running',total:contacts.length,sent:0,failed:0,errors:[],startedAt:new Date().toISOString()};jobs.set(jobId,job);res.json({success:true,jobId:jobId,total:contacts.length});setImmediate(async function(){var si=0;for(var i=0;i<contacts.length;i++){if(job.status==='stopped')break;var c=contacts[i];var smtp=smtps[si%smtps.length];si++;var html=(htmlBody||'').replace(/\{\{name\}\}/gi,c.name||'').replace(/\{\{email\}\}/gi,c.email||'').replace(/\{\{st\}\}/gi,c.address||'').replace(/\{\{id\}\}/gi,c.unique_id||'').replace(/\{\{[^}]+\}\}/g,'');var subj=(subject||'').replace(/\{\{name\}\}/gi,c.name||'').replace(/\{\{email\}\}/gi,c.email||'').replace(/\{\{[^}]+\}\}/g,'');var from=fromName?fromName+' <'+smtp.email+'>':smtp.email;var mailOpts={from:from,to:c.email,subject:subj,html:html,text:textBody||html.replace(/<[^>]+>/g,'')};if(jobAttachments.length>0)mailOpts.attachments=jobAttachments;try{await sendOne(smtp,mailOpts);job.sent++}catch(e){job.failed++;job.errors.push({email:c.email,error:e.message})}await new Promise(function(r){setTimeout(r,150)})}job.status='completed';job.stoppedAt=new Date().toISOString()})})
app.get('/status/:id',auth,function(req,res){var j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Not found'});res.json(j)})
app.post('/stop/:id',auth,function(req,res){var j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Not found'});j.status='stopped';j.stoppedAt=new Date().toISOString();res.json({success:true})})
app.listen(process.env.PORT||3000,'0.0.0.0',function(){console.log('Mailflow Agent ready on port '+(process.env.PORT||3000))})